### PR TITLE
fix(Toast): Added checking for `prefers-reduced-motion`

### LINKED ISSUE #927: Add `prefers-reduced-motion` check to Toasts
All animations for Toasts were moved from CSS package to React package. `prefers-reduced-motion` check is missing in React.

### PR DESCRIPTION
**Pull request by adamhock**
## Changes

Removes transitions for `Toast` component when `prefer-reduced-motion` is active.
Closes #927 

## Testing

1. Open up the `Toast` story in storybook
2. Right click & Inspect page
3. Click the 3 dot menu in the top right of the inspect panel & select More tools > Rendering
4. In the Rendering tab, find Emulate CSS Media feature prefers-reduced-motion
5. See the changes made by opening and closing different toasts

ToastReduceMotionDemo

## Docs

Changeset added

### CODE REVIEW

File: packages/itwinui-react/src/core/Toast/Toast.tsx [hunk 1]
```diff
@@ -169,27 +169,37 @@ export const Toast = (props: ToastProps) => {
     return { translateX, translateY };
   };
 
+  const motionOk = getWindow()?.matchMedia(
+    '(prefers-reduced-motion: no-preference)',
+  )?.matches;
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Toast/Toast.tsx:174]: `useMediaQuery` would be better here. it is more optimized.

```jsx
  const motionOk = useMediaQuery('(prefers-reduced-motion: no-preference)');
```

Comment (adamhock) [reply packages/itwinui-react/src/core/Toast/Toast.tsx]: This has been changed

**Review by FlyersPh9 — APPROVED** [review]
Wait for an approval from someone more versed in React before merging, but looks good to me!

**Comment by elephantcatdog** [comment]
Just a question - is the changeset not something to be mentioned in the 'Docs' section of the PR description?

**Review by elephantcatdog — COMMENTED** [review]
When I tested it, I got some funny movement where the toast bobs up and down: 

https://user-images.githubusercontent.com/37936169/213798247-a073cad7-57b3-4978-b43b-6a17611bd95f.mp4

This doesn't seem to happen for you. Does the full page modal work for you or does it fail like in #1022? I wonder if they're related.

**Comment by rohan-kadkol** [comment]
> Just a question - is the changeset not something to be mentioned in the 'Docs' section of the PR description?

If a changeset is included, then I think we should mention it _Docs_ portion of the PR description. Because not mentioning it could mean the author accidentally didn't include one even when there's a user facing change.

Also, the template talks about changesets under the Docs section and also that's how we're doing it in other PRs. (https://github.com/iTwin/iTwinUI/pull/1011, https://github.com/iTwin/iTwinUI/pull/1006)

File: packages/itwinui-react/src/core/Toast/Toast.tsx [hunk 2]
```diff
@@ -169,27 +175,35 @@ export const Toast = (props: ToastProps) => {
...
     <Transition
       timeout={{ enter: 240, exit: animateOutTo ? 400 : 120 }}
       in={visible}
       appear={true}
       unmountOnExit={true}
       onEnter={(node: HTMLElement) => {
-        node.style.transform = 'translateY(15%)';
-        node.style.transitionTimingFunction = 'ease';
+        if (motionOk) {
+          node.style.transform = 'translateY(15%)';
```
Comment (adamhock) [inline packages/itwinui-react/src/core/Toast/Toast.tsx:188]: Because this `translateY` doesn't happen anymore on when reduced motion is active, the screenshots will be slightly altered as they were taking during this translation in `onEnter`, but not after the transformation in `onEntered`.

**Review by elephantcatdog — COMMENTED** [review]
~Why did the test images change? I wouldn't have thought that they would change.~

Didn't see your comment, whoops

File: packages/itwinui-react/src/core/Toast/Toast.tsx (hunk 2 above)
Comment (mayank99) [reply packages/itwinui-react/src/core/Toast/Toast.tsx:188]: you could try an alternate approach where instead of conditionally applying styles, you could conditionally set the transition duration, i.e. something like "normal duration if motion ok. 0.001s if reduced motion preferred".

doing that might avoid the issues with positioning.

Comment (elephantcatdog) [reply packages/itwinui-react/src/core/Toast/Toast.tsx:188]: Do the tests run with reduced motion on? Huh

Comment (adamhock) [reply packages/itwinui-react/src/core/Toast/Toast.tsx:188]: I'm mistaken. These tests do not run with reduced motion on. The toasts are not transitioning properly when reduced motion is off (the default). I'll work on a fix

Comment (adamhock) [reply packages/itwinui-react/src/core/Toast/Toast.tsx:183]: These image changes have been reverted aside from one. There is a slight horizontal change in the toast buttons on the Position Changed story. I'm not sure why

File: .changeset/nice-mayflies-eat.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@itwin/itwinui-react': minor
```
Comment (mayank99) [inline .changeset/nice-mayflies-eat.md:2]:
```suggestion
'@itwin/itwinui-react': patch
```

**Review by mayank99 — APPROVED** [review]

**Review by elephantcatdog — APPROVED** [review]
🎉

File: .changeset/nice-mayflies-eat.md (hunk 3 above)
Comment (adamhock) [reply .changeset/nice-mayflies-eat.md]: Fixed
