### PR TITLE
Truncate first `select-tag` in `select-tag-container`

### LINKED ISSUE #1633: Select : Incorrect tags being displayed when we have long string as dropdown menu item in Multi Select component
#### Describe the bug (actual behavior)
For multi select component if we have long string in dropdown menu option(I set the width as 300px for select component) and we select the same entry then instead of showing tag with "1item(s)", it shows "2items(s)" though no other item is selected.
chrome_kKvz6Momt3

#### Expected behavior
Select should show "1item(s)" selected instead of showing "2items(s)" if string length exceeds the dropdown width else it should display selected string in tag. 

#### Reproduction
[Link to a minimal repro: ](https://codesandbox.io/s/react-typescript-forked-7zvs6d?file=/src/App.tsx)

##### Steps to reproduce
1. Create a file with below piece of code
 ```
 import "./styles.css";
import {
  Label,
  LabeledSelect,
  MenuItem,
  MiddleTextTruncation,
  Select,
  SelectValueChangeEvent
} from "@itwin/itwinui-react";
import React from "react";
import { useCallback, useEffect, useMemo, useState } from "react";

export default function App() {
  const [selectedOption, setSelectedOption] = useState<string[]>();
  const list = useMemo(
    () => [
      {
        label: "instance long long very long text ABCDEFGHIJKLMNOPQRSTUVWXYZ",
        value: "Instance1Value"
      },
      { label: "Instance2", value: "Instance2Value" },
      { label: "Instance3", value: "Instance3Value" },
      { label: "Instance4", value: "Instance4Value" },
      { label: "Instance5", value: "Instance5Value" },
      { label: "Instance6", value: "Instance6Value" },
      { label: "Instance7", value: "Instance7Value" },
      { label: "Instance8", value: "Instance8Value" },
      { label: "Instance9", value: "Instance9Value" },
      { label: "Instance10", value: "Instance10Value" },
      { label: "Instance11", value: "Instance11Value" },
      { label: "Instance12", value: "Instance12Value" },
      { label: "Instance13", value: "Instance13Value" },
      { label: "Instance14", value: "Instance14Value" }
    ],
    []
  );
  const onChange = useCallback(
    (value: string, event: SelectValueChangeEvent) => {
      let options = selectedOption ? [...selectedOption] : [];
      if (event === "added") {
        options.push(value);
      }
      if (event === "removed") {
        options = options.filter((option) => option !== value);
      }
      setSelectedOption(options);
    },
    [selectedOption]
  );
  const textRenderer = React.useCallback(
    (truncatedText: string, originalText: string) => (
      <span title={truncatedText !== originalText ? originalText : undefined}>
        {truncatedText}
      </span>
    ),
    []
  );

  return (
    <div>
      <Label displayStyle="inline">Form :</Label>
      <div style={{ width: "300px" }}>
        <Select<string>
          placeholder={"Select"}
          value={selectedOption}
          onChange={onChange}
          options={list}
          className="property-select-list"
          multiple
          itemRenderer={(option, itemProps) => (
            <MenuItem>
              <MiddleTextTruncation
                text={option.label}
                textRenderer={textRenderer}
              />
            </MenuItem>
          )}
        />
      </div>
    </div>
  );
}

```
2. Run the application
3. Select long string from multiselect dropdown
4. user will see incorrect tag being displayed

### PR DESCRIPTION
**Pull request by rohan-kadkol**
## Changes

Fixes #1633.

* Truncate the `select-tag` when there is only one tag in `select-tag-container`

When just one long list item is selected:

|Before #1634|Current (after #1634)|With this PR|
|:-|:-|:-|
|image|image|image|
|incorrect overflow count|showing just one long cut-off tag = we can't see the overflow count = we don't know how many items are really selected|it still shows only one long tag, but the tag is truncated instead of cutoff = we know there is only one selected tag|

Unrelated:
* Removed an extra space from a test name

## Testing

All tests still pass

## Docs

Added changeset

### CODE REVIEW

File: packages/itwinui-react/src/core/Select/SelectTagContainer.tsx
Comment (mayank99) [inline packages/itwinui-react/src/core/Select/SelectTagContainer.tsx:1]: i'm not sure about this solution, shouldn't we use CSS to truncate the overflowing text instead of showing "+1 items"? would be much more useful that way.

Comment (rohan-kadkol) [reply packages/itwinui-react/src/core/Select/SelectTagContainer.tsx:1]: To confirm, so with CSS, are you suggesting something along these lines:

```scss
@mixin iui-select-tag {
  // ...
  
  // Truncate the first tag
  &:first-child {
    max-inline-size: 100%;
  }
}
```

Or another solution would be using a `<MiddleTextTruncation>` for the first tag. But I guess that is not recommended ([docs](https://itwinui.bentley.com/docs/select#truncation))?

image

Comment (mayank99) [reply packages/itwinui-react/src/core/Select/SelectTagContainer.tsx:1]: `::only-child` selector would probably work better.

this is how i expect it to look:


Middle text truncation should definitely be avoided except when needed for very specific use cases.

File: packages/itwinui-css/src/select/select.scss [hunk 1]
```diff
@@ -102,11 +102,16 @@
...
+  // Truncate when only one tag is present
+  &:only-child {
+    max-inline-size: 100%;
+  }
 }
 
 @mixin iui-select-tag-label {
   @include tag.iui-tag-label;
-  display: inline-flex;
+  display: block;
```
Comment (mayank99) [inline packages/itwinui-css/src/select/select.scss:114]: i think flexbox was needed for centering. do you want to try `display: flex`?

File: .changeset/brown-turtles-drop.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@itwin/itwinui-css': patch
```
Comment (mayank99) [inline .changeset/brown-turtles-drop.md:2]:
```suggestion
'@itwin/itwinui-css': patch
'@itwin/itwinui-react': patch
```

File: packages/itwinui-css/src/select/select.scss [hunk 3]
```diff
@@ -102,11 +102,16 @@
   align-items: center;
   block-size: 80%;
   max-block-size: calc(var(--iui-size-s) * 3);
+
+  // Truncate when only one tag is present
+  &:only-child {
+    max-inline-size: 100%;
```
Comment (mayank99) [inline packages/itwinui-css/src/select/select.scss:108]: now i'm wondering if we even need the `:only-child`. shouldn't the max-width always be 100%, regardless of whether it's the only child?

File: .changeset/brown-turtles-drop.md (hunk 2 above)
Comment (rohan-kadkol) [reply .changeset/brown-turtles-drop.md:2]: Ohh, to confirm, since this is a CSS only change, do we need to add `itwinui-react`?

File: packages/itwinui-css/src/select/select.scss (hunk 1 above)
Comment (rohan-kadkol) [reply packages/itwinui-css/src/select/select.scss:114]: I had changed `inline-flex` to `block` to get the ellipses to show up. Because with `inline-flex` or `flex`, the ellipses didn't show up:

|`block`|`flex`/`inline-flex`|
|-|-|
|image|image|

File: packages/itwinui-css/src/select/select.scss (hunk 3 above)
Comment (rohan-kadkol) [reply packages/itwinui-css/src/select/select.scss]: Ohh, that's true, removed `:only-child` (https://github.com/iTwin/iTwinUI/pull/1716/commits/877b8b0df93811001f5c8a41e680b338bb07ca22)

File: .changeset/brown-turtles-drop.md (hunk 2 above)
Comment (mayank99) [reply .changeset/brown-turtles-drop.md:2]: yes, because itwinui-react produces its own stylesheet

File: packages/itwinui-css/src/select/select.scss (hunk 1 above)
Comment (mayank99) [reply packages/itwinui-css/src/select/select.scss:110]: flexbox children will refuse to collapse beyond their "real" width by default. could you try adding `min-inline-size: 0` to the child element?

Comment (rohan-kadkol) [reply packages/itwinui-css/src/select/select.scss:110]: As discussed, `select-tag-label` does not have any child tag.

image

So, I went ahead with `display: block` instead of `display: inline-flex`, and so also removed the previous `align-items` attribute on `select-tag-label`. (https://github.com/iTwin/iTwinUI/pull/1716/commits/e1956468dbee883b57c17a253f2dbe6ee66a94db)

**Review by mayank99 — APPROVED** [review]
