### PR TITLE
Fix `Popover` floating content automatically resizing when opened

### LINKED ISSUE #2523: Dropdown menu: strange transition when placed on the right of the page
### Describe the bug (current behavior)

Bug introduced in 3.18.
When `DropdownMenu` trigger button is placed on the right of the screen and menu contains `MenuExtraContent` element that displays some text (the longer the text, the longer the animation), clicking on the button causes content to slowly "grow" from the right of the screen.

https://github.com/user-attachments/assets/ee53e1ac-13c4-41f1-bec6-7a293e45dc95

### Expected Behavior

No transition

### Link to minimal repro

https://stackblitz.com/edit/github-jsfernvs

### Steps To Reproduce

_No response_

### Package Version

- [x] I'm using the latest version of iTwinUI.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by r100-stack**
## Changes

Fixes #2523.

The regression started from [`3.18.0`](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.18.0) that included #2491 that started the use of layout (`top` and `left`) instead of transforms for the Floating UI positioning of `Popover`. Since `Popover` or `usePopover()` are used in other components too (e.g. `DropdownMenu`), this issue was noticed in other components too.

To fix it, removed `transform: false` to undo #2491, at least partially. Since the default value of `transform` is `true`, all components that use `usePopover` effectively have `transform: true`. To fix the bug #2491 was trying to fix, this PR adds `transform: false` to just `Popover`. (https://github.com/iTwin/iTwinUI/pull/2524#discussion_r2082360692).

This fixes the issue for all components using `usePopover()`. However `Popover` and components that use `Popover` will still have the automatic resizing issue because of setting `transform: false`.

To fix that issue in `Popover`, this PR followed the suggestion mentioned in the [Floating UI docs](https://floating-ui.com/docs/usefloating#transform) of adding a `width` when using the layout mode instead of transforms:

> When using layout instead of transforms, ensure that the floating element has a fixed width or sets a `width: max-content` to prevent it from resizing.

~This PR adds `width: max-content` which can be overridden by consumers, if needed. Also added some comment explanation and links near the fix.~ No longer adding `width: max-content` on the react side as inline styles. ([#2524 (comment)](https://github.com/iTwin/iTwinUI/pull/2524#discussion_r2058587069)).

Instead, this PR adds a new `iui-popover` class to `Popover` that adds `width: max-content` to the floating content. Since this style is layered, it can be overriden easily by consumers, if needed.

## Testing

Tested manually using the consumer's sandbox to confirm the resizing no longer happens. Didn't add a test for the bug fix since this case seemed too specific.

Added a unit test to confirm that `iui-popover` is applied to `Popover`. Didn't add this check for components that use `usePopover()` internally.

## Docs

Added a `patch` react changeset for the bug fix and a `minor` css changeset for the new `iui-popover` class.

### CODE REVIEW

File: packages/itwinui-react/src/core/Popover/Popover.tsx [hunk 1]
```diff
@@ -306,6 +306,10 @@ export const usePopover = (options: PopoverOptions & PopoverInternalProps) => {
       interactions.getFloatingProps({
         ...userProps,
         style: {
+          // Since using layout instead of transform for floating styles, setting width to prevent unintended resizing (https://github.com/iTwin/iTwinUI/issues/2523)
+          // https://floating-ui.com/docs/usefloating#transform
+          width: 'max-content',
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Popover/Popover.tsx:311]: CSS would be a better place for this to allow for easier overrides. If the issue is only in `Menu`, can we apply it there?

Comment (mayank99) [reply packages/itwinui-react/src/core/Popover/Popover.tsx:311]: Ah in that case I think a new `iui-popover` to be applied unconditionally on `Popover` should be good.

API size is not something we need to worry too much about when it comes to CSS classes. We will likely stop publishing the CSS library altogether in the future.

---

If we already have a shadow-root in `Popover`, we _could_ use that, but it would be clearer to keep things in CSS. In the near future, we might need to add more styles to handle `maxBlockSize` too (related: https://github.com/iTwin/iTwinUI/pull/2517#discussion_r2049706317).

Comment (mayank99) [reply packages/itwinui-react/src/core/Popover/Popover.tsx]: Still missing this part of the [earlier suggestion](https://github.com/iTwin/iTwinUI/pull/2524#discussion_r2058626151):

> Maybe we can re-enable `transform` but only for popovers that can't have nested popovers inside them (e.g. `DropdownMenu`, `SplitButton`).

Comment (mayank99) [reply packages/itwinui-react/src/core/Popover/Popover.tsx]: It is confusing to add an implicit `iui-popover` class to non-`Popover` components. If we want to add this class, it should be added explicitly to each of those components. But even then, the name still would be confusing. And it might cause unintended effects when we extend this class for `Popover`-specific functionality (like the `maxBlockSize` issue mentioned above).

If we take a step back, the only reason `inline-size: max-content;` is necessary is to address the issue caused by [`transform: false`](https://floating-ui.com/docs/usefloating#transform). And the only reason `transform: false` was added in #2491 is to support a nested `Dialog` (which uses `position: fixed`) inside `Popover`. Since it is invalid to nest any dialogs/popovers inside other components that use `usePopover`, we can continue to use `transform: true` in those components and avoid such issues.

Comment (mayank99) [reply packages/itwinui-react/src/core/Popover/Popover.tsx]: That looks good. Can you revert all unrelated changes to reduce the diff?

**Review by mayank99 — APPROVED** [review]
LGTM after https://github.com/iTwin/iTwinUI/pull/2524#discussion_r2082412697. Also, PR description should mention the `transform: false` change.

This can be included in 3.18.2.

File: packages/itwinui-react/src/core/Popover/Popover.tsx (hunk 1 above)
Comment (mayank99) [reply packages/itwinui-react/src/core/Popover/Popover.tsx]: `className` is still being passed into `getFloatingProps` in `Popover.tsx`.

**Review by mayank99 — APPROVED** [review]
LGTM! Let's release 3.18.2 right after merging this.
