### PR TITLE
Remove `react-transition-group` dependency

### LINKED ISSUE #2199: findDOMNode deprecation warning with newest react 18 version
### Describe the bug (current behavior)

With newest React 18 version when certain iTwinUi-react components are used and app is in strict mode, an error is logged into the console: findDOMNode is deprecated in StrictMode.

The error is coming from 'react-transition-group' package that is used in WithCSSTransition component. As I understand according to issue https://github.com/reactjs/react-transition-group/issues/904 this can be fixed on iTwinUI side.

### Expected Behavior

_No response_

### Link to minimal repro

_No response_

### Steps To Reproduce

1. Create an app that is using React 18 and is wrapped in strict mode.
2. Use one of the affected components, e.g. WithCSSTransition 
3. You should be seeing the error in browser console when affected component is rendered

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by r100-stack**
## Changes

Prerequisite for #2387. Fixes #2199.

This PR removes the dependency to the now mostly unmaintained [`react-transition-group`](https://github.com/reactjs/react-transition-group). This has been our plan for a while now because of running into issues with it and having to find workarounds (e.g. #1835). Since React 19 has now removed the deprecated `findDOMNode()` that `react-transition-group` moving away from this package is needed to support React 19 in #2387.

Affected components:
* Dialog/Modal: Exit animation removed temporarily since it's difficult to implement cleanly in JS.
* Toast: Used the [`animate()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate) function to implement the same animation in JS.

---

There were some animations that used to work in previous v3 versions and also in v2. Some of these animations stopped working in the previous few versions before this PR. So, I just removed the code for those animations since they anyways weren't working even before this PR. Some of these animations include:
* <details><summary>Table with subcomponent</summary>

  |v2.12.26|v3.16.0|
  |-|-|
  |<video src="https://github.com/user-attachments/assets/efde123f-e7b8-48a3-89a3-43e748b2aba8" />|<video src="https://github.com/user-attachments/assets/cfa055fe-5aa8-462d-8c41-24840325b386" />|

  </details> 

* <details><summary>SideNavigation with submenu</summary>

  |v2.12.26|v3.16.0|
  |-|-|
  |<video src="https://github.com/user-attachments/assets/6eafdcd3-90c3-4bbc-87c2-adacfd69d555" />|<video src="https://github.com/user-attachments/assets/6fc300df-3e51-439d-8fad-be8933fb7ec5" />|

  </details>

This PR also deprecates the `react-transition-group` related CSS classes: `.iui-enter`, `.iui-enter-active`, `.iui-exit`, `.iui-exit-active` since they are no longer needed.

## Testing

Confirmed whenever react-transition-group was used or at least was intended to be used, there is no visual change after this PR. The only exception is where we purposefully removed the animation temporarily (Dialog/Modal exit animation).

## Docs

Added *minor* react and css changesets.

It is minor for css because of class deprecations. It is a minor for react since `react-transition-group` could be a dependency used in users' apps too and so could affect their dependency resolution. An additional reason is that the `Dialog`/`Modal`'s exit animation is removed temporarily.

## After PR TODO:

* [ ] Try to avoid the effect by moving the sync based on visibility logic to where the visibility changes ([#2391 (comment)](https://github.com/iTwin/iTwinUI/pull/2391#discussion_r1924248045)).
* [x] Confirm if there is some flakiness in the Toasts react tests ([#2312 (review)](https://github.com/iTwin/iTwinUI/pull/2312#pullrequestreview-2582637920)).

### CODE REVIEW

File: packages/itwinui-react/src/core/Toast/Toast.tsx [hunk 1]
```diff
@@ -172,73 +171,135 @@ export const Toast = (props: ToastProps) => {
...
+  }, [
+    animateIn,
+    animateOut,
+    animateOutTo,
+    calculateOutAnimation,
+    isVisible,
+    motionOk,
+    onRemove,
+    prevIsVisible,
+  ]);
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Toast/Toast.tsx:277]: First of all, we should not be using an Effect here. We should animate in the same place where the visible state changes.

However, it might be difficult to untangle the mess that exists, so we could keep the Effect as a (hopefully temporary) hack. We should still reduce the number of dependencies in this array, by moving some of them inside Effect, and making some of them `useLatestRef` if we don't need their reactive values. Also, it would be good to move this into a custom hook.

File: packages/itwinui-react/src/core/Toast/Toaster.test.tsx [hunk 2]
```diff
@@ -19,6 +19,15 @@ import {
...
 const mockOnClick = vi.fn();
 
+// Set reduced motion to not trigger animations since JSDom doesn't mock `animate()`.
+const originalMatchMedia = window.matchMedia;
+beforeAll(() => {
+  window.matchMedia = vi.fn().mockReturnValue({ matches: false });
+});
+afterAll(() => {
+  window.matchMedia = originalMatchMedia;
+});
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Toast/Toaster.test.tsx:29]: Can we use `animate?.()` to get around this issue? Otherwise our consumers will also need to add this mock.

File: packages/itwinui-react/src/core/Dialog/DialogMain.tsx [hunk 3]
```diff
@@ -203,36 +202,53 @@ export const DialogMain = React.forwardRef((props, ref) => {
...
+      setShouldBeMounted(true);
+    } else {
+      onExit();
+
+      // Wait for the animation to end
+      setTimeout(() => {
+        setShouldBeMounted(false);
+      }, 600);
+    }
+  }
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Dialog/DialogMain.tsx:244]: Can we use a callback ref to get precise timing of when the element mounts/unmounts?

e.g. something like this:

```jsx
ref={
  React.useCallback((element) => {
    if (element) {
      onEnter();
    } else {
      onExit();
    }
  }, [])
}
```

File: packages/itwinui-react/src/core/Dialog/Dialog.tsx [hunk 4]
```diff
@@ -42,37 +41,50 @@ const DialogComponent = React.forwardRef((props, ref) => {
...
+    if (isOpen) {
+      setShouldBeMounted(true);
+    }
+    // Wait for DialogMain to receive the isOpen=false to properly handle its exit. E.g. move focus to trigger.
+    else {
+      setTimeout(() => {
+        setShouldBeMounted(false);
+      }, 600);
+    }
+  }, [isOpen]);
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Dialog/Dialog.tsx:58]: Hmm, I don't think we should have this additional state. `isOpen` can be used as the source of truth if we call `onExit()` after the animation ends.

File: apps/react-workshop/cypress-visual-screenshots/baseline/Toasts.test.ts-Informational.png
Comment (mayank99) [inline apps/react-workshop/cypress-visual-screenshots/baseline/Toasts.test.ts-Informational.png:1]: Why did these images change? Looks like there is a slight change in positioning, which I think might be not intentional.

File: .changeset/rude-books-drum.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@itwin/itwinui-css': minor
+---
+
+Animation related classes are made now deprecated: `.iui-enter`, `.iui-enter-active`, `.iui-exit`, `.iui-exit-active`.
```
Comment (mayank99) [inline .changeset/rude-books-drum.md:5]: typo? "made now deprecated" → "now made deprecated"

File: packages/itwinui-react/src/core/Dialog/Dialog.tsx (hunk 4 above)
Comment (mayank99) [reply packages/itwinui-react/src/core/Dialog/Dialog.tsx:58]: Sorry I meant to say `onClose()`, not `onExit()`.

Basically, we need to ensure that `isOpen` will be true when the entry animation starts and remain true until until the exit animation ends.

This means we need to 
1. Animate out the dialog when a "close trigger" is activated (i.e. "❌" button or Esc key).
2. After the animation, call `onClose()` (probably in `onExit()`) for removing it from DOM.

If this requires large code changes, let's remove the animation code from this PR and re-introduce it in a future PR. In the meantime, the dialog entry animation should still work, which is good.

File: packages/itwinui-react/src/core/Toast/Toast.tsx (hunk 1 above)
Comment (mayank99) [reply packages/itwinui-react/src/core/Toast/Toast.tsx]: What I mean is, we should execute this code next to the place where we are updating the state, rather than using an Effect to create a chained computation based on the state value. It's similar to the idea of [moving logic out of Effects into event handlers](https://react.dev/learn/separating-events-from-effects).

For the custom hook, I have a few points of feedback:
- The `shouldBeMounted` state can be moved into the hook and returned by it, so that `setShouldBeMounted` does not need to be passed into it.
- `useLatestRef` might be overused in this scenario. We should be more thoughtful about it. `useLatestRef` is most useful for frequently-changing unmemoized dependencies.
  - `thisElement` is already ref and does not need additional `useLatestRef`.
  - `motionOk` is a simple boolean value that likely won't change often, so doesn't need additional `useLatestRef`.
  - `calculateOutAnimation` could be moved inside the Effect so that it doesn't need `useLatestRef`.
- readability: When accepting lots of parameters, use an object instead of positioned arguments.
  - Depending on your preference, all of the parameters can be passed into a single argument, or you can have two arguments: first one would be `isVisible` and second one would be the object containing the rest of the information.
- readability: When defining multiple functions inside an Effect, consider using a hoisted `function` (instead of arrow function) located below the main Effect logic, so that it's easier to read.

Comment (mayank99) [reply packages/itwinui-react/src/core/Toast/Toast.tsx]: I think you want to use `animteOutToRef` inside the Effect and remove `animateOutTo` from the dependency array

Comment (mayank99) [reply packages/itwinui-react/src/core/Toast/Toast.tsx]: It looks like you did the opposite of what I suggested, but it's ok. `animateOutTo` is an `HTMLElement`, so it should remain stable for the common use-case (animating toasts into the notification bar).

File: packages/itwinui-react/src/core/Dialog/Dialog.tsx (hunk 4 above)
Comment (mayank99) [reply packages/itwinui-react/src/core/Dialog/Dialog.tsx:58]: > I think only `isOpen` is what decides whether a dialog is open or not. Because if users pass `isOpen={false}` and don't update `isOpen` in the `onClose` that they pass to it, the dialog doesn't close even if the "❌" button is clicked.

This should be considered a consumption error. The `onClose()` exists for a reason and should not be ignored. I think #1976 would help avoid such issues in the future, but for now it should be ok to assume proper usage of `onClose()` + `isOpen`.

> Here, by the time onExit's logic is executed, `dialogRef.current` becomes `null`. If not having the exit animations, we'd need to remove that if statement.

We could keep the if-statement but move it before we call `onClose()`. This should ensure that `dialogRef.current` is still available, because `isOpen` will not be `false` until the next render. If we are calling `onClose()` in multiple places, it might be useful to create a wrapper over it, named e.g. `requestClose()`.

> Also, I'm wondering, should we check for `setFocus` in `onExit` similar to how we do it in onEntered?

I don't think so. We never want a situation where the end user's focus gets lost after closing the dialog. Additionally, `setFocus` should default to `true` (#1998), so that consumers don't have to think about it.

Comment (mayank99) [reply packages/itwinui-react/src/core/Dialog/Dialog.tsx]: If `requestClose` is only needed by `Dialog.Main` and its descendants, we can create a different context in `DialogMain`.

It's also confusing to store the `requestClose` in an `onClose` field in the root context. It should be renamed or its value should be reverted back to `props.onClose`.

File: packages/itwinui-react/src/core/Dialog/DialogMain.tsx [hunk 6]
```diff
@@ -204,34 +234,16 @@ export const DialogMain = React.forwardRef((props, ref) => {
...
-          dialogRef.current?.contains(
-            dialogRef.current?.ownerDocument.activeElement,
-          )
-        ) {
-          previousFocusedElement.current?.focus();
-        }
+    <DialogMainContext.Provider
+      value={{
+        beforeClose,
       }}
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Dialog/DialogMain.tsx:240]: nit 1: Context values should be memoized.

```suggestion
      value={React.useMemo(() => ({ beforeClose }), [beforeClose])}
```

(check formatting when committing)

File: packages/itwinui-react/src/core/Dialog/DialogMain.tsx [hunk 7]
```diff
@@ -158,6 +161,33 @@ export const DialogMain = React.forwardRef((props, ref) => {
...
+
+  const mountRef = React.useCallback(
+    (element: HTMLElement | null) => {
+      /** Focuses dialog when opened. */
+      if (element) {
+        onEnter();
+      }
+    },
+    [onEnter],
+  );
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Dialog/DialogMain.tsx:189]: nit 2: This can be made more readable by moving the comment and using an if-condition.

```suggestion
  /** Focuses dialog when opened. */
  const onEnter = React.useCallback(() => {
    previousFocusedElement.current = dialogRef.current?.ownerDocument
      .activeElement as HTMLElement;
    if (setFocus) {
      dialogRef.current?.focus({ preventScroll: true });
    }
  }, [dialogRef, previousFocusedElement, setFocus]);

  /** Brings back focus to the previously focused element when closed. */
  const beforeClose = React.useCallback(() => {
    if (
      dialogRef.current?.contains(
        dialogRef.current?.ownerDocument.activeElement,
      )
    ) {
      previousFocusedElement.current?.focus();
    }
  }, [dialogRef, previousFocusedElement]);

  const mountRef = React.useCallback(
    (element: HTMLElement | null) => {
      if (element) {
        onEnter();
      }
    },
    [onEnter],
  );
```

File: packages/itwinui-react/src/core/Dialog/DialogTitleBar.tsx [hunk 8]
```diff
@@ -56,6 +59,11 @@ export const DialogTitleBar = Object.assign(
 
     const { onPointerDown } = useDialogDragContext();
 
+    const onClick = React.useCallback(() => {
+      dialogMainContext?.beforeClose();
+      onClose?.();
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Dialog/DialogTitleBar.tsx:64]: We were previously passing the click event into `onClose`.

File: packages/itwinui-react/src/core/Toast/Toast.tsx
Comment (mayank99) [inline packages/itwinui-react/src/core/Toast/Toast.tsx:1]: Should we have a changeset for Toast? Maybe can be combined with the other changesets.

e.g. Something like:

> Removed dependency on `react-transition-group`. Notable changes in components:
>  - `useToaster`: Animations have been reworked to directly use the web animations API.
>  - `Dialog` and `Modal`: Exit animations have been temporarily removed.

**Review by mayank99 — APPROVED** [review]

**Review by smmr-dn — APPROVED** [review]
