### PR TITLE
fix Table `columnOrder` resetting incorrectly

### LINKED ISSUE #1899: Table initial state not setting column order properly.
### Describe the bug (current behavior)

When setting up the columnOrder prop in table's initial state it's being ignored, and table is rendering columns in the order of the columns array.

### Expected Behavior

Table render columns in the order provided to initial state.

### Link to minimal repro

https://stackblitz.com/edit/github-y5zcvc?file=src%2FDraggableColumns.tsx

### Steps To Reproduce

_No response_

### Anything else?

```"@itwin/itwinui-react": "2.12.24"```

### PR DESCRIPTION
**Pull request by mayank99**
## Changes

Fixes #1899.

The root cause was that the initial value of `lastPassedColumns` is `[]` so it was always resetting the columns. `[]` is never valid so I've added a simple check for it.

## Testing

Tested in playground (using [linked sandbox](https://stackblitz.com/edit/github-y5zcvc?file=src%2FDraggableColumns.tsx)) and added unit test.

## Docs

N/A

### CODE REVIEW

**Review by rohan-kadkol — APPROVED** [review]

File: packages/itwinui-react/src/core/Table/Table.tsx [hunk 1]
```diff
@@ -717,7 +717,10 @@ export const Table = <
...
   React.useEffect(() => {
     // Check if columns have changed (by value)
-    if (JSON.stringify(lastPassedColumns.current) !== JSON.stringify(columns)) {
+    if (
+      lastPassedColumns.current.length > 0 &&
+      JSON.stringify(lastPassedColumns.current) !== JSON.stringify(columns)
+    ) {
       instance.setColumnOrder([]);
     }
     lastPassedColumns.current = columns;
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Table/Table.tsx:726]: Some comments for future:

1. We should try to avoid stringifying columns like this. It can be expensive and error-prone. In our _new_ Table we could require always passing an id, or find a way to compare the internal ids.
 
2. We should maybe create a hook for this "previous state" pattern.
   ```jsx
   function usePreviousState<T>(state: T, onChange: () => void): React.Ref<T>;
   ```

Comment (rohan-kadkol) [reply packages/itwinui-react/src/core/Table/Table.tsx:726]: Sounds good, linked this comment in https://github.com/iTwin/iTwinUI/issues/1144.
