### PR TITLE
Fix "ref is not a prop" React warning

### LINKED ISSUE #2566: `ref` is not a prop warning in `DropdownMenu` component
### Describe the bug (current behavior)

Using a basic sample code from https://itwinui.bentley.com/docs/dropdownmenu#basic produces a warning in a console:
```
Warning: [object Object]: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.
```

Related issue: https://github.com/iTwin/appui/issues/1335

### Expected Behavior

Expected no warning to be logged.

### Link to minimal repro

https://stackblitz.com/edit/github-4rvefqep?file=src%2FApp.tsx,src%2Fmain.tsx

### Steps To Reproduce

1. Open the sandbox
2. Open the console
3. Observe the error

### Package Version

- [x] I'm using the latest version of iTwinUI.

### Anything else?

Only reproducible with React v18

### PR DESCRIPTION
**Pull request by r100-stack**
## Changes

Fixes #2566.

Adds an if-statement to check if `React.version.startsWith("19.")`. If `true`, does `element.props.ref`. Else, does `element.ref`.

Tried to avoid the if statement to keep things simple but other approaches such as using `||` as it was before this PR gave the warning in React 19 or in versions of React 18 and below, depending on the order. i.e. `element.props.ref || element.ref` will give a warning in React 18 and below and `element.ref || element.props.ref` will give a warning in React 19.

`DropdownMenu` seems to have been a component affected by this bug. But since part of this fix of this PR is in `cloneElementWithRef` which is used in other components too, this PR might fix those other components too.

## Testing

Tested manually in React 17, 18, and 19. The following errors don't appear for [DropdownMenu's basic demo](https://itwinui.bentley.com/docs/dropdownmenu#basic):

React 19:
```
Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.
```

React 18 and earlier:
```
`ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.
```

## Docs

Added `patch` changeset.

### CODE REVIEW

File: packages/itwinui-react/src/utils/functions/react.ts [hunk 1]
```diff
@@ -23,8 +23,13 @@ export const cloneElementWithRef = (
     return children;
   }
 
-  // Supporting React 19 and 18
-  const childrenRef = children.props?.ref || (children as any)?.ref;
+  // Supporting React 19 and earlier versions
+  const childrenRef = (() => {
+    if (React.version.startsWith('19.')) {
```
Comment (mayank99) [inline packages/itwinui-react/src/utils/functions/react.ts]: `React.version` does not look like a documented API. I think we should avoid using it to make assumptions about the future.

Instead, we can reverse the approach:
1. Make a utility function `isReact17or18()`.
2. Use `element.ref` if the condition matches.

Comment (r100-stack) [reply packages/itwinui-react/src/utils/functions/react.ts]: > Make a utility function `isReact17or18()`.

To confirm, how are you suggesting this function should be implemented? Because doing something like `return !('ref' in element.props)` still gives the warning in React 18.

Also, doing something like `import { version as reactVersion } from 'react/package.json';` gives an error in VSCode. It says the issue is because the `"module"` is `"NodeNext"`.

Comment (mayank99) [reply packages/itwinui-react/src/utils/functions/react.ts]: I'm not suggesting avoiding `React.version` altogether, I'm only suggesting not relying on it being available in the _future_. We know for a fact that it exists in previous versions (which will no longer be updated).

So something like this should work:

```js
import * as React from "react";

const _React = React;

function isReact17or18() {
  const version = _React.version?.split(".")?.[0];
  return ["17", "18"].includes(version);
}
```

The `_React` reassignment helps bypass bundler optimizations, and the `?` operator helps at runtime.

Comment (r100-stack) [reply packages/itwinui-react/src/utils/functions/react.ts]: Ohh, great, implemented and tested that it works (https://github.com/iTwin/iTwinUI/pull/2571/commits/128f0a4daa44a427d43df6c8c66821724f5331af).

File: packages/itwinui-react/src/core/Select/Select.tsx [hunk 2]
```diff
@@ -838,18 +839,20 @@ const SelectListbox = React.forwardRef((props, forwardedRef) => {
...
-      ) : (
-        child
-      ),
-    );
+    return React.Children.map(childrenProp, (child, index) => {
+      if (React.isValidElement<Record<string, any>>(child)) {
+        // Supporting React 19 and earlier versions
+        const ref = (() => {
+          if (isReact17or18) {
+            return child.props.ref;
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Select/Select.tsx]: This needs to be reversed.

Additionally, it doesn't need the IIFE anymore.

Comment (r100-stack) [reply packages/itwinui-react/src/core/Select/Select.tsx]: Oops, fixed. Also changed to use the ternary operator instead of IIFE. (https://github.com/iTwin/iTwinUI/pull/2571/commits/f35bfc611d432383e60a9e2bd46c1e52f20daf67)
