### PR TITLE
fix(Input): Added `htmlSize` prop to set native `size` attribute

### LINKED ISSUE #973: v3: Input size prop overrides native `size` attribute
native input has size prop, which we drop out. Need to rename our prop and return the native prop.

### PR DESCRIPTION
**Pull request by adamhock**
## Changes

Added `htmlSize` prop to the `Input` component which handles the native `size` attribute in `<input>`.

Closes #973 

## Testing

Added new unit test

## Docs

Updated documentation to explain new prop
Changeset added

### CODE REVIEW

File: packages/itwinui-react/src/core/Input/Input.tsx [hunk 1]
```diff
@@ -11,26 +11,26 @@ export type InputProps = {
   /**
    * Modify size of the input.
    */
-  size?: 'small' | 'large';
+  localSize?: 'small' | 'large';
```
[the remark this answers is not in the document]
Comment (gretanausedaite) [reply packages/itwinui-react/src/core/Input/Input.tsx:14]: `inputSize` | `boxSize` ? localSize sounds like internal variable.

**Comment by mayank99** [comment]
maybe we can leave `size` as-is and then add `htmlSize` for native attribute? we can explain the difference in the jsdoc and our documentation site.

reason: it is way more common to use the `size` prop to change height, than it is to use the native `size` attribute to constrain width.

**Comment by adamhock** [comment]
> maybe we can leave `size` as-is and then add `htmlSize` for native attribute? we can explain the difference in the jsdoc and our documentation site.
> 
> reason: it is way more common to use the `size` prop to change height, than it is to use the native `size` attribute to constrain width.

Great idea! This has been updated.

**Review by LostABike — COMMENTED** [review]
Everything looks fine, I just have a question. The native `size` attribute of `<input>` is to determine how many characters will be visible right? However, because we have `inline-size = 100%` within our `<Input/>` component styling, setting this `size` (or `htmlSize`) will not do anything unless user specifically override our component `inline-size`. Is this intended?

File: .changeset/shaggy-hornets-enjoy.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@itwin/itwinui-react': major
```
Comment (gretanausedaite) [inline .changeset/shaggy-hornets-enjoy.md:2]: I believe this is not major change? We are adding attribute, not changing current API.

File: packages/itwinui-react/src/core/Input/Input.tsx [hunk 3]
```diff
@@ -12,6 +12,10 @@ export type InputProps = {
    * Modify size of the input.
    */
   size?: 'small' | 'large';
+  /**
+   * Modify the `size` attribute of the `<input>` element.
```
Comment (gretanausedaite) [inline packages/itwinui-react/src/core/Input/Input.tsx:16]: Maybe mention it's for native attr.

**Review by gretanausedaite — APPROVED** [review]
LGTM.

**Comment by adamhock** [comment]
> > The native `size` attribute of `<input>` is to determine how many characters will be visible right? However, because we have `inline-size = 100%` within our `<Input/>` component styling, setting this `size` (or `htmlSize`) will not do anything unless user specifically override our component `inline-size` styling. Is this intended?
> 
> It is intended that our input fills up the width of the container, because otherwise it would have some weird default width. So yeah, to make use of this `size` (`htmlSize`) attribute, the developer would need to use `width: unset` or `inline-size: unset`. We could mention this in the jsdoc comment for our prop.

Could we apply `width: unset` or `inline-size: unset` stylings to `<Input>` if an `htmlSize` prop is passed?

File: packages/itwinui-react/src/core/Input/Input.tsx (hunk 3 above)
Comment (adamhock) [reply packages/itwinui-react/src/core/Input/Input.tsx]: Fixed

File: .changeset/shaggy-hornets-enjoy.md (hunk 2 above)
Comment (adamhock) [reply .changeset/shaggy-hornets-enjoy.md]: Updated

**Comment by mayank99** [comment]
> Could we apply `width: unset` or `inline-size: unset` stylings to `<Input>` if an `htmlSize` prop is passed?

Overengineering it imo. I do not expect this attribute to be used commonly enough to justify the extra code. If somebody finds the current behavior confusing, we can always revisit in the future.

Oh and slight typo in [`6ef5d74`](https://github.com/iTwin/iTwinUI/pull/1419/commits/6ef5d740ebd9c98e8aed4dca406f6c44d05b671c) btw. Should say "properties" instead of "attributes".

**Review by LostABike — APPROVED** [review]
LGTM :D
