### PR TITLE
Fix `Table` bug of trying to add `scrollToRow` to DOM

### LINKED ISSUE #2513: Table: scrollToRow prop is passed to DOM element
### Describe the bug (current behavior)

React warns about passing `scrollToRow` property when rendering `Table` component and passing it `scrollToRow` prop.

```
Warning: React does not recognize the `scrollToRow` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrolltorow` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

### Expected Behavior

No warning

### Link to minimal repro

https://stackblitz.com/edit/stackblitz-starters-e5d5gftz?file=app%2Fpage.tsx

### Steps To Reproduce

Render `Table` component and pass it `scrollToRow` property.

### Package Version

- [x] I'm using the latest version of iTwinUI.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by r100-stack**
## Changes

Fixes #2513.

Destructs `scrollToRow` from `props` and uses it somewhere in the code to make use of that variable.

## Testing

Confirmed manually that that console error no longer shows.

## Docs

Added `patch` changeset.

### CODE REVIEW

File: packages/itwinui-react/src/core/Table/Table.tsx [hunk 1]
```diff
@@ -446,6 +446,7 @@ export const Table = <
     getRowId,
     caption = 'Table',
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Table/Table.tsx:447]: Will we fix `caption` in another PR?

**Review by mayank99 — APPROVED** [review]

File: packages/itwinui-react/src/core/Table/Table.tsx (hunk 1 above)
Comment (r100-stack) [reply packages/itwinui-react/src/core/Table/Table.tsx:447]: Fixed in https://github.com/iTwin/iTwinUI/pull/2538.
