### PR TITLE
Close menu on clicking nested `MenuItem`s in `Tile.MoreOptions`

### LINKED ISSUE #2451: Clicking on submenu items in Tile's MoreOptions doesn't close the menu
### Describe the bug (current behavior)

In the `MoreOptions` component of Tile, we pass in a list of `MenuItem`s. However, when a `MenuItem` contains submenu items, clicking on a submenu item does not automatically close the `MoreOptions` menu. It also doesn't expose the `close` function for manual closing on the users side (similar to `DropdownMenu` menuItems)

### Expected Behavior

`MoreOptions` menu should automatically close when its submenu item is clicked, and/or have the `close` prop exposed

### Link to minimal repro

https://stackblitz.com/edit/github-zvoxjsmy-hsis35df?file=src%2FApp.tsx

### Steps To Reproduce

1. Create a `Tile` with `MoreOptions`
2. Create a `MenuItem` with `submenu` item
3. Pass the `MenuItem` with `submenu` item into Tile's `MoreOptions`
4. Click to open the `MoreOptions` menu in `Tile`
5. Click on the `MenuItem` to expose `submenu` item
6. Click on `submenu` item

### Package Version

- [x] I'm using the latest version of iTwinUI.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by r100-stack**
## Changes

Fixes #2451.

Upon discussing internally, looks like handling the MenuItem closing on click instead of exposing the `close` function to the user was intentional.

The existing `cloneElement` approach works only for top-level MenuItems within `Tile.MoreOptions`. So, this PR uses a context approach to automatically close the menu upon clicking even the nested `MenuItem`s. 

This PR adds a context called `DropdownMenuCloseOnClickContext`. This wraps around a `DropdownMenu`. When set to true, any descendant `MenuItem` click will close the menu.

If we ever decide to allow "closing menu on menuitem click" as a prop, we can replace this context's provider with that prop to `DropdownMenu` in `Tile.MoreOptions`.

This PR adds another context called `DropdownMenuContext` to pass the close function down.

## Testing

Added e2e test.

## Docs

Added changeset.

## After PR TODOs:

- [ ] Consider changing the type of `children` to be compatible with `menuItems` ([#2452 (comment)](https://github.com/iTwin/iTwinUI/pull/2452#discussion_r1980184851)).

### CODE REVIEW

File: packages/itwinui-react/src/core/Menu/MenuItem.tsx [hunk 1]
```diff
@@ -111,6 +112,7 @@ export const MenuItem = React.forwardRef((props, forwardedRef) => {
   }
 
   const parentMenu = React.useContext(MenuContext);
+  const tileMoreOptionsContext = React.useContext(TileMoreOptionsContext);
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Menu/MenuItem.tsx:115]: `Tile` depends on `Menu`/`MenuItem` but the vice-versa is not true, so it would be nice to decouple this component from `Tile`.

We could create a context in `Menu`/`MenuItem` such that when it's set (to `true`), the `Menu` will automatically close. Then we can provide this context from `Tile.MoreOptions`.

As a bonus, this approach would allow `Tile.MoreOptions` to stay uncontrolled (i.e. it no longer needs to pass `visible` to `DropdownMenu`).

Comment (mayank99) [reply packages/itwinui-react/src/core/Menu/MenuItem.tsx]: Instead of manually inheriting the context value across all `Menu`s, it might be simpler to provide a single context value for the whole tree in `DropdownMenu`.

In the next minor release, we could even offer this as a prop. I can imagine it being useful for when `menuItems` is used with a React node (instead of a `(close) => []` function).

Comment (mayank99) [reply packages/itwinui-react/src/core/Menu/MenuItem.tsx]: 1. Remove `topmostClose` and `MenuItemCloseContext` from `Menu.tsx`.
2. Create a simple boolean context in `DropdownMenu.tsx`.
3. Use the context directly in `MenuItem.tsx`.

If you think about it, "closing" is a feature of the `DropdownMenu`, not the `Menu`, so it makes sense to move the context up there.

File: packages/itwinui-react/src/core/Menu/MenuItem.tsx [hunk 2]
```diff
@@ -134,6 +142,11 @@ export const MenuItem = React.forwardRef((props, forwardedRef) => {
       return;
     }
 
+    // If DropdownMenuCloseOnClickContext's value = true, should close the `DropdownMenu` when the `MenuItem` is clicked
+    if (dropdownMenuCloseOnClickContext) {
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Menu/MenuItem.tsx:146]: nit: This comment can be avoided if we make the variable name self-explanatory.

`dropdownMenuCloseOnClickContext` ➡️ `shouldCloseMenuOnClick`

File: packages/itwinui-react/src/core/Tile/Tile.tsx [hunk 3]
```diff
@@ -384,40 +387,33 @@ const TileMoreOptions = React.forwardRef((props, forwardedRef) => {
...
+        {...rest}
       >
-        <IconButton
-          styleType='borderless'
-          size='small'
-          aria-label='More options'
-          {...buttonProps}
+        <DropdownMenu
+          onVisibleChange={setIsMenuVisible}
+          menuItems={children as React.ReactElement<any>[]}
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Tile/Tile.tsx:404]: Why is this type assertion needed?

**Review by mayank99 — APPROVED** [review]
