### PR TITLE
make virtual tree nodes equally wide

### LINKED ISSUE #2330: Tree horizontal scroll
### Describe the bug (current behavior)

Selected and hovered TreeNode styling is off when Tree component has horizontal scroll.

### Expected Behavior

It was possible to add horizontal scroll to the Tree component in 3.12.0 version and styling of TreeNode was alright: https://stackblitz.com/edit/github-mmlry8-kslxf8

### Link to minimal repro

https://stackblitz.com/edit/github-mmlry8-pkdhkj

### Steps To Reproduce

1. Expand Tree couple levels deep.
2. Select nodes from different levels.
3. Scroll to the right.
4. Selected nodes in different levels have different size outline and active background coloring.

### Package Version

- [x] I'm using the latest version of iTwinUI.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mayank99**
## Changes

Fixes #2330 by setting an explicit width on the virtualizer root. This width is periodically calculated as the maximum width of all _mounted_ elements inside the virtualizer.

This is done inside the virtualizer's [`onChange`](https://tanstack.com/virtual/latest/docs/api/virtualizer#onchange) callback, which I had to debounce because otherwise it executes several times when scrolling. Layout reads/writes are expensive operations so we should try to minimize them. I'm also updating the style imperatively instead of using React state (which would require additional re-render each time).

## Testing

Manually tested that the linked issue is fixed. Verified also that the Tree returns to its original width after a wider node is collapsed.

[Preview](https://itwin.github.io/iTwinUI/2633/react/?story=tree--virtualized-with-horizontal-scroll&theme=dark) (try expanding one of the deeply nested nodes and compare the behavior with [`main` branch](https://itwin.github.io/iTwinUI/react/?story=tree--virtualized-with-horizontal-scroll&theme=dark))

| Before | After |
| --- | --- |
| Screenshot showing tree nodes that don't stretch to fill the available width | Screenshot showing tree nodes that stretch to fill the available width |

## Docs

Added changeset.

### CODE REVIEW

File: packages/itwinui-react/src/core/Tree/Tree.tsx [hunk 1]
```diff
@@ -415,11 +416,29 @@ const VirtualizedTree = React.forwardRef(
       [flatNodesList],
     );
 
+    /** Sets the virtualizer width to that of the widest element, so that all items are same width. */
+    const onVirtualizerChange = React.useMemo(
```
Comment (r100-stack) [inline packages/itwinui-react/src/core/Tree/Tree.tsx:420]: I noticed that the tree width doesn't decrease when the wider nodes are collapsed. Maybe that's just something on my end? Because I see in your PR description this behavior was working on your end. Or maybe it's some newer commit?

https://github.com/user-attachments/assets/ec52e536-7761-47aa-8912-18afaf3b2da9

Comment (mayank99) [reply packages/itwinui-react/src/core/Tree/Tree.tsx:420]: Ah, good catch. I think I was testing a different case previously, because I just discovered that the virtualizer's `onChange` does not always get called when collapsing nodes (which is strange in itself, because the nodes are getting unmounted).

[`850e828`](https://github.com/iTwin/iTwinUI/pull/2633/commits/850e8286054b6805901ed8171012bbe06a21edd4): Fixed by calling `onVirtualizerChange` explicitly whenever `onExpanded` is called, and by resetting the virtualizer root's width before taking new measurements.

<details>
<summary>Screen recording</summary>

https://github.com/user-attachments/assets/a9792bad-2bef-4cac-bc6a-8c956487a386

</details>

**Review by FlyersPh9 — APPROVED** [review]

**Comment by FlyersPh9** [comment]
Thank you @r100-stack for reviewing, we appreciate your help!

**Comment by mayank99** [comment]
Are you using multiple trees by any chance? Or setting `overflow: auto` on individual nodes? Because there should only be a single horizontal scrollbar at the bottom.
