### PR TITLE
Floating elements try preferring best fit

### LINKED ISSUE #2597: TablePaginator: Popover position is incosistent
### Describe the bug (current behavior)

Trying to set the page size on TablePaginator renders the popover inconsistently. When the popover is triggered for the first time, it renders above the button (upwards). On all subsequent interactions, the popover appears below the button.

Image

### Expected Behavior

The popover should be shown in a consistent way.

### Link to minimal repro

https://itwin.github.io/iTwinUI/react/?story=table--with-paginator

### Steps To Reproduce

1.  Click on the rows per page button (notice the popover opens upwards)
2. Click elsewhere so the popover closes
3. Click again on the rows per page button 
4. Notice it now opens downwards.

### Package Version

- [x] I'm using the latest version of iTwinUI.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by r100-stack**
## Changes

Fixes #2597, at least tries to.

Upon internal discussion, we decided to try setting the `flip` padding to 5 since it seems to fix this issue. This temporary solution might be sufficient if this issue is a one-off. However, if there still exist cases where the floating elements' positioning is unideal, a better solution might need to be thought of.

Upon reading the docs for using the `size` middleware with `flip`, I realized that they tell to pass the same padding to both middlewares. I then realized that the bug is not fixed because of 5 as the `flip` padding. Rather, it gets fixed whenever the `flip` padding is one more than the `size` padding.

Thus, added a comment to explain that the mismatch in the paddings is intentional. ~Also added a TODO since it's like a temporary fix. Can remove the TODO from this PR but leave the comment contents, if needed.~ Removed the TODO (https://github.com/iTwin/iTwinUI/pull/2624#discussion_r2246287485).

## Testing

Confirmed that the Table's [WithPaginator story](https://itwin.github.io/iTwinUI/react/?story=table--with-paginator) now shows the floating content above instead of below, thus no longer causing the issue.

## Docs

Added patch changeset.

### CODE REVIEW

File: packages/itwinui-react/src/core/Popover/Popover.tsx [hunk 1]
```diff
@@ -245,7 +245,8 @@ export const usePopover = (options: PopoverOptions & PopoverInternalProps) => {
       () =>
         [
           middleware.offset !== undefined && offset(middleware.offset),
-          middleware.flip && flip({ padding: 4 }),
+          // TODO: Temporary solution that sets flip padding to one higher than size padding to prefer best fit.
+          middleware.flip && flip({ padding: 5 }),
```
Comment (mayank99) [inline packages/itwinui-react/src/core/Popover/Popover.tsx]: This comment is not accurate or even useful.

- "best fit" is too vague; maybe we can mention the issue as well.
- I don't consider to be a "temporary solution" because that would imply we plan to come back to this (which we don't, _unless_ we find other issues).

Something like the following would be more appropriate:

```suggestion
          middleware.flip && flip({ padding: 5 }), // one higher than `size` padding to prefer best fit (see #2597)
```

**Review by mayank99 — APPROVED** [review]
