### PR TITLE
fix(Inputs): border color changes to status color on hover

### LINKED ISSUE #624: Inputs: Status border color on hover is not aligned
Textarea
image
Input
image
Select
image

On hover, select gets borders colored according to status, while others do not.

@gretanausedaite suggested that all the inputs have a change of color as this would add some colors to our design system.

### PR DESCRIPTION
**Pull request by adamhock**
- Changes made to `Input` and `Textarea` components so that their border gets colored according to status when they're hovered.
- This is to match the behavior seen in the `Select` component.

Input Before
image
Input After
image

Textarea Before
image
Textarea After
image

Closes #624

### CODE REVIEW

**Comment by FlyersPh9** [comment]
Can you add tests to `input.js` & `textarea.js` to check hover & focus on inputs with & without status?

**Review by elephantcatdog — COMMENTED** [review]
No additional comments

**Comment by adamhock** [comment]
> Can you add tests to `input.js` & `textarea.js` to check hover & focus on inputs with & without status?

Tests have been added

File: packages/itwinui-css/backstop/scenarios/input.js [hunk 1]
```diff
@@ -13,4 +13,20 @@ module.exports = [
   scenario('Type Without Label', {
     selectors: ['#demo-no-label'],
   }),
+  scenario('State hover in default', {
+    actions: [hover('#test-input')],
+    selectors: ['#demo-input'],
```
Comment (FlyersPh9) [inline packages/itwinui-css/backstop/scenarios/input.js:18]: Can you add `viewports: [{ width: 800, height: 600 }],` to all of these new tests?

File: packages/itwinui-css/backstop/scenarios/input.js [hunk 2]
```diff
@@ -13,4 +13,20 @@ module.exports = [
...
+  }),
+  scenario('State hover with status', {
+    actions: [hover('#test-input-with-status')],
+    selectors: ['#demo-input-with-status'],
+  }),
+  scenario('State focus in default', {
```
Comment (FlyersPh9) [inline packages/itwinui-css/backstop/scenarios/input.js:24]: You can reduce the amount of test images by covering hover & focus with a single test.  Here's an example from `carousel.js`:
```js
// Hover & focus states
scenario('State hover & focus', {
  actions: [hover('#test-1'), focus('#test-2')],
  selectors: ['#demo-default'],
}),
```

Comment (adamhock) [reply packages/itwinui-css/backstop/scenarios/input.js:21]: Since multiple `iui-input-container` elements aren't wrapped in another element that isn't the entire demo page, I think it's best to just have separate test images for focus and hover

File: packages/itwinui-css/backstop/scenarios/input.js (hunk 1 above)
Comment (adamhock) [reply packages/itwinui-css/backstop/scenarios/input.js]: Added

Comment (FlyersPh9) [reply packages/itwinui-css/backstop/scenarios/input.js]: Can you add these to textarea as well?

Comment (adamhock) [reply packages/itwinui-css/backstop/scenarios/input.js]: Good catch! Fixed

**Review by FlyersPh9 — APPROVED** [review]

**Review by elephantcatdog — COMMENTED** [review]
It looks like tests for hc dark, hc light, and light are missing for 
image

**Review by elephantcatdog — APPROVED** [review]
> It looks like tests for hc dark, hc light, and light are missing

I found them; they just don't render on github for me for some reason.
