### PR TITLE
fix Select positioning after first render

### LINKED ISSUE #1679: `Select` menu is offset when opened for 2nd time
#### Describe the bug (actual behavior)

`<Select popoverProps={{ placement: 'bottom-end' }} />`
1. Click once, menu opens properly
2. Close menu
3. Click, menu opens with offset

Similar bug is visible in storybook too.
<https://itwin.github.io/iTwinUI/react/?story=input--select--basic>
If you open it for seconds time, big empty space appears below it

#### Expected behavior

Menu opens in same position every time

#### Reproduction
Link to a minimal repro: 
<https://stackblitz.com/edit/stackblitz-starters-ywppax>

##### Steps to reproduce
`<Select popoverProps={{ placement: 'bottom-end' }} />`
1. Click once, menu opens properly
2. Close menu
3. Click, menu opens with offset

#### Additional information

itwinuibug

### PR DESCRIPTION
**Pull request by mayank99**
## Changes

fixes #1679

This PR effectively undoes #1661 which was the cause of the issue. In short: after the menu closes, we were still holding onto the old DOM reference, thus causing issues with calculating new position when menu re-opens (it's a new DOM node).

After investigating, I found that the real cause of #1657 was that we were not memoizing the random value used in `useId` fallback, so it was returning a different value on each render, and this was causing an infinite loop (presumably because we are using the id in a `key`, which resets all state). The simple fix is to memoize the random value.

## Testing

tested that Select stories work correctly

tested `placement: 'bottom-end'` working correctly in vite playground, in both react 17 and 18.

## Docs

added changeset.

### CODE REVIEW

File: packages/itwinui-react/src/core/utils/hooks/useId.ts [hunk 1]
```diff
@@ -18,4 +18,5 @@ export const useId = () => {
 // This is needed to avoid bundlers trying to import non-existing export.
 // Read more: https://github.com/webpack/webpack/issues/14814
 const _React = React;
-const useUniqueValue = _React.useId ?? (() => getRandomValue(10));
+const useUniqueValue =
+  _React.useId ?? (() => React.useMemo(() => getRandomValue(10), []));
```
Comment (mayank99) [inline packages/itwinui-react/src/core/utils/hooks/useId.ts:22]: should we backport this to v2? seems like a major oversight, and most of our users are not using react 18 yet.

File: .changeset/sixty-seahorses-count.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@itwin/itwinui-react': patch
+---
+
+Fixed an issue where `Select` was being positioned incorrectly after first render.
```
Comment (rohan-kadkol) [inline .changeset/sixty-seahorses-count.md:5]: To confirm, do we need to say the *dropdownMenu* was positioned incorrectly?

```suggestion
Fixed an issue where `Select`'s dropdownMenu was being positioned incorrectly after its first render.
```

**Review by rohan-kadkol — COMMENTED** [review]
Confirmed that #1657 and #1679's issues are fixed on React 18👍

This may not be related to this PR, but I noticed some UI jump when clicking on the select for the first time when the Select has `popoverProps={{ placement: 'bottom-end' }}`. The dropdown menu seems to be stuck to the right, and then instantly spreads across all the width. (You might need to manual move the video slider slowly to notice it.)


[35.webm](https://github.com/iTwin/iTwinUI/assets/45748283/c3682eab-1211-4811-9ecf-4f350147bb7b)

File: .changeset/sixty-seahorses-count.md (hunk 2 above)
Comment (mayank99) [reply .changeset/sixty-seahorses-count.md:5]: how about this?
```suggestion
Fixed an issue where `Select` menu was being positioned incorrectly after first render.
```

**Review by mayank99 — COMMENTED** [review]
>  The dropdown menu seems to be stuck to the right, and then instantly spreads across all the width.

this is probably because it needs an extra render to match the width. not sure if there's a better way as it's done using floating-ui middleware

File: .changeset/sixty-seahorses-count.md (hunk 2 above)
Comment (rohan-kadkol) [reply .changeset/sixty-seahorses-count.md:5]: Sounds good, but I feel with the `'s`, the meaning is a bit clearer. Also, without the `its`, it could be unclear if the "first render" is of the *Select component* or of *its menu*.

```suggestion
Fixed an issue where `Select`'s menu was being positioned incorrectly after its first render.
```

But maybe I'm nitpicking 😅 Your code suggestion is good too.

**Review by rohan-kadkol — APPROVED** [review]

**Review by rohan-kadkol — COMMENTED** [review]
**UPDATE**:
Confirmed the #1657 and #1679's issues are fixed on React 17 too.

Also noticed that Select's menu jump issue that I mentioned earlier does not happen in React 17.

File: packages/itwinui-react/src/core/utils/hooks/useId.ts (hunk 1 above)
Comment (rohan-kadkol) [reply packages/itwinui-react/src/core/utils/hooks/useId.ts:23]: Yes, I feel we should, especially since it's just 1-2 lines. Although #1679 and #1657 are I think v3 only bugs, this backport might fix some bug that we are not aware of.
